### PR TITLE
Clean up and restoration

### PR DESCRIPTION
**Pull request by xunkar**

### CODE REVIEW

**Comment by masanasake** [comment]
I feel like we're in competition constantly, but I don't mind at all; what do you think of these two? I think they're better than what's in both of our pull requests currently. 
Super Mario Land 2 - 6 Golden Coins (USA, Europe) (Rev 2)
Super Mario Land (World) (Rev 1)

**Comment by xunkar** [comment]
Hmm. SML2 is probably sourced from a higher res, but the colors are a little off (easy to fix) and it looks like someone used a strong denoiser that thinned the edges a little too much. I'll try to make a quick correction.

SML1 however is on par with the PR in terms of source resolution, but mine has better color ramps (look at the pyramids for example, the white lines are barely visible because the white levels are too high).

**Comment by masanasake** [comment]
Works for me. Also, I see you've got a better Pokemon Yellow than the one I submitted previously; Anything that can be done for Pokemon Red that is more true to the original?

**Comment by xunkar** [comment]
I submitted this one previously for Pokémon Red

https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy/8dd7e306ffbf7ce58986076b395a19c4422950a9/Named_Boxarts/Pokemon%20-%20Red%20Version%20(USA%2C%20Europe)%20(SGB%20Enhanced).png

As far as I can tell it is the original.

**Comment by masanasake** [comment]
These were fan made as far as I know. This looks like it's probably the origin. https://www.deviantart.com/jadelune/art/Pokemon-Red-Version-Game-Boy-HQ-Box-Art-593872975 
I think they generally look decent, except they over-did it with the filters on Red; needed the colors. The originals look more like watercolor. There aren't great options for them, and they're hard to clean up manually.
Not sure that this is the best version there is, but this is what's its supposed to look like.  Compare the style of the one you uploaded to Pokemon Blue. 
image

**Comment by masanasake** [comment]
Pokemon - Red Version (USA, Europe) (SGB Enhanced)
This is the best one I found, and originally it was a weird brown at the top and bottom left. Increased contrast to make it look a bit more accurate.

**Comment by xunkar** [comment]
I partly disagree. I'm looking at an original box here https://i.ytimg.com/vi/RWP9Joc-Ia4/maxresdefault.jpg and the background is highly contrasted. What could be done is grafting some of Charizard's body texture onto the vector repro. But it's gonna be difficult to get rid of the scans artifact on such patterned gradients.

**Comment by masanasake** [comment]
I think you've got about half of my request already, considering revising mine. Would you mind taking a look at these two and just adding it to yours if you want to make changes to one or the other?
This one may be a reproduction and is higher quality, but the colors look like they've been messed with:
Wario Land - Super Mario Land 3 (World)

This one I'm fairly certain is original and I tried cleaning it up by hand:
Wario Land - Super Mario Land 3 (World)

Note: OFFICIAL vs ORIGINAL. I don't know the difference between the two honestly. Regional?

**Comment by xunkar** [comment]
From experience the "ORIGINAL" wording is EU and the "OFFICIAL" wording is US. You're right the first one has odd details. The game pak logo has a bolder font, and the colors are weird. What's puzzling is that the colors are not uniformly offset. I'll try my best.

**Comment by xunkar** [comment]
I tweaked the colors based on this capture https://i.pinimg.com/originals/de/63/05/de630547870ca8a91af91ca60ad8e856.jpg and I think we're closer to the truth. Unfortunately I can't do much about the sticker for now, it's difficult working with small types at this resolution.

**Comment by masanasake** [comment]
Great, thank you. I updated my PR so there's no duplicates between us. One last favor: Any chance you can rework the background on Pokemon red? Just seems very dark: 
image

Everyone under the sun seems to have messed with this cover art, but no one has messed with this guide.I'm pretty sure these are the most accurate colors. The cover art at the bottom is low res and has a bunch of stray marks at the top that isn't easily cleaned up, otherwise I think it'd be the best bet. Feel free to ignore me; just a thought... 
image
image

**Comment by masanasake** [comment]
Would you consider letting this one replace the one in your PR? I took it from what looks like an unadulterated original (note the R instead of TM and the complete black outline on the head) and did the ol' pixel by pixel cleanup on the top two line of pixels, the bottom line, and any stray marks. Fairly certain this is the most accurate to the original, again referencing the guidebook and what looks like the majority of what exists online. I'm assuming you had to place the old image over the fan image to create the high contrast one currently? Literally using a combination of Paint 3D and basic MS photo viewer for these things, so it's the best I can do...
Pokemon - Red Version (USA, Europe) (SGB Enhanced)

**Comment by xunkar** [comment]
This is looking good I'll update it.

**Comment by xunkar** [comment]
As I suspected the red channel was clipped upwards resulting in a loss of data. I've slightly regraded the ramp for a bit more nuances, however this is not yet as rich as the original. Still, the original might have this issue too, impossible to tell. Hope you'll be alright with this small adjustment too.

**Pull request merged**
